<a href="https://colab.research.google.com/github/soongnie/aieyes1/blob/main/aieyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
arr = np.array(list1)
arr10 = arr * 10

print(arr10)

[10 20 30 40]


In [3]:
import numpy as np

price = [
    [100, 80, 70, 90],
    [120, 110, 100, 110]
]

arr2 = np.array(price)

arr2[0]
arr2[1]

array([120, 110, 100, 110])

In [4]:
from pandas import Series

arr = [0, 1, 2, 3]
s = Series(arr)
print(s)

0    0
1    1
2    2
3    3
dtype: int64


In [5]:
data = [100, 200, 300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [6]:
data = [100, 200, 300]
index = ['월', '화', '수']
s = Series(data, index)
print(s)

월    100
화    200
수    300
dtype: int64


In [7]:
data = [100, 200, 300]
index = ['월', '화', '수']
s = Series(data, index)

print(s.index)
print(s.values)

Index(['월', '화', '수'], dtype='object')
[100 200 300]
